export const metadata = {
  title: "Authentication",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "red", padding: "20px" }}>
          <p>footer</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "green", padding: "20px" }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
