import { Metadata } from "next";



export const metadata: Metadata = {
  title: {
    default:"Next.js-Tutorial", // acts as a fallback for any child routes they don't specify their own title
    template:"%s | Next.js-Tutorial",// its usefull when we want to add consistent prefix or suffix to the title this property applies to child routes

  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
       
        {children}
        </body>
    </html>
  );
}
