export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header style={{ backgroundColor: "wheat", padding: "20px" }}>
        <p>Header</p>
      </header>
      {children}
      <footer style={{ backgroundColor: "yellow", padding: "20px" }}>
        <p>Footer</p>
      </footer>
    </>
  );
}
