import { Metadata } from "next";



export const metadata: Metadata = {
  title: {
    default:"Next.js-Tutorial", // acts as a fallback for any child routes they don't specify their own title
    template:"%s | Next.js-Tutorial",// its usefull when we want to add consistent prefix or suffix to the title this property applies to child routes
    absolute: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "20px" }}>
          <p>footer</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "20px" }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
